### ISSUE TITLE
Review code

### ISSUE THREAD

**Issue by driskull** [Esri/application-base-js#2]
@jcfranco can you review this file?

https://github.com/Esri/application-base-js/blob/master/ApplicationBase.ts

**Comment by jcfranco** [comment]
* Some variables are typed as `any`. E.g., `defaultConfig`, `defaultSettings`
* Need to use `declared` decorator, [as shown here](https://github.com/dojo/typings/tree/master/examples/basicApp/src/app), for creating classes.
* `locale`, under Properties section, should be typed as `string` to be consistent with other properties.
* Some promise-result types can be narrowed down instead of using `any`.
* Properties from `settings` can be renamed using deconstruction:

  ```ts
  const { environment: environmentSettings, group: groupSettings, /* ... */ } = settings;
  ```
* [This](https://github.com/Esri/application-base-js/blob/master/ApplicationBase.ts#L325-L338) and [this](https://github.com/Esri/application-base-js/blob/master/ApplicationBase.ts#L341-L344) can be simplified by not checking for `length`.
* Private methods can be extracted into separate utilities
* Some conditional logic can be simplified:

  ```ts
  const isEsriAppsPath = esriAppsPathIndex !== -1; // `? true : false;` not needed
  ```
* Typo: `_foramatUrlParamValue ` -> `_formatUrlParamValue `
* `ApplicationBaseItemPromises` and `Direction` could be moved to `interfaces.d.ts`

#### Minor

* Rename: 
  * `RTLLocales` -> `rtlLocales`
  * `_setupCORS` -> `_setUpCORS`
  * `webmapX` -> `webMapX`/`websceneX` -> `webSceneX`
  * `_queryItem` -> `_loadItem`? (applies to others too)
  * `ptl` -> `portal` and type as any when setting `helperServices`
* `checkSignIn` can be dropped
* New line after property name headers

**Comment by driskull** [comment]
👍 thanks!! I'll work on these

**Comment by driskull** [comment]
Updated with: 44e9695aae1ab21b888f800b55f9be17a5cf93c5

Thanks @jcfranco!

I'll think about how I can move more functions into separate modules. I don't want these functions to be documented so maybe a support module that starts with an underscore?

**Comment by jcfranco** [comment]
> I don't want these functions to be documented so maybe a support module that starts with an underscore?

👍  Although, I think you could still split them up without the underscore.

**Comment by driskull** [comment]
I got all the TypeScripty things updated
